% Initialisation of the zhawines document class based on scrreport
% -----------------------------------------------------------------
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{zhawines}[2015/02/26 ZHAW InES Standard Report]
\LoadClass[oneside,10pt,parskip=half]{scrreprt}


% Definition of special options for the class
% -----------------------------------------------------------------

% Language settings to use babel correctly and adapt the title page
% and references
\DeclareOption{ngerman}{
  \PassOptionsToClass{ngerman}{babel}
}

\DeclareOption{english}{
  \PassOptionsToClass{english}{babel}
}

\ProcessOptions

% Definition of the used packages (special packages add in teh 
% specific document)
% -----------------------------------------------------------------
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\usepackage{ifthen}
\usepackage{url}
\usepackage{scrpage2}
\usepackage{scrhack}
\usepackage{listings}
\usepackage{pdfpages}


% Definition of the layout of the document, pagesize and headings
% -----------------------------------------------------------------

\geometry{a4paper, top=30mm, left=30mm, right=25mm, bottom=30mm,headsep=10mm,footskip=10mm}

\renewcommand*{\chapterheadstartvskip}{\vspace{0.5cm}}
%\renewcommand*{\chapterheadendvskip}{\vspace{0.5cm}}

\newcommand{\headings}{
	\pagestyle{scrheadings}
	\pagenumbering{arabic}

	%header / footer 
	\clearscrheadfoot
	\automark[section]{chapter}
	\renewcommand{\chapterpagestyle}{scrheadings}
	\ohead{\headmark}
	\ihead{ZHAW - InES}



	\cfoot{\thepage}
	\ifoot{\the\day.\the\month.\the\year}
	\setfootsepline{0.4pt}
	\setheadsepline{0.4pt}
}


% Redefinition of the \maketitle command to create the ZHAW
% title page, added an email parameter (\email)
% -----------------------------------------------------------------
\newcommand{\Email}{info.ines@zhaw.ch}
\newcommand{\email}[1]{\renewcommand{\Email}{#1}}
\renewcommand{\and}{\\}  % separate the authors with a line break

% Commands for the additional roles for Bachelor Thesis
\newcommand{\Betreuer}{Hans Betreuer}
\newcommand{\betreuer}[1]{\renewcommand{\Betreuer}{#1}}
\newcommand{\Nebenbetreuer}{Fritz Nebelbetreuer}
\newcommand{\nebenbetreuer}[1]{\renewcommand{\Nebenbetreuer}{#1}}


\renewcommand{\maketitle}{
\thispagestyle{empty}
\pagestyle{empty}

% Place the logo on top left
\begin{flushleft}
	\ifthenelse{\equal{\languagename}{\string ngerman}}
	{\includegraphics[height=30mm]{images/logos/de-zhaw-ines-rgb.png}}
	{\includegraphics[height=30mm]{images/logos/en-zhaw-ines-rgb.png}} 
\end{flushleft}

\vskip 8em
\vskip 3em

% Title of the report
\begin{flushleft}
	{\huge \textbf{\@title}}
	\rule{\textwidth}{0.8mm}
\end{flushleft}

\vskip 5em
\vskip 2em

% School and Institute
\begin{flushleft}
	\LARGE
	\ifthenelse{\equal{\languagename}{\string ngerman}}
	{\textsc{Zürcher Hochschule für Angewandte Wissenschaften}}
	{\textsc{Zurich University of Applied Sciences}} \\
    \vspace*{1cm}
    \Large
    \textsc{Institute of Embedded Systems}
\end{flushleft}

% Authors and Date
\vskip 5em
\renewcommand{\arraystretch}{1.5}

\begin{tabular}{ p{3cm} l }
\ifthenelse{\equal{\languagename}{\string ngerman}}{Autoren}{Authors} & \parbox[t]{5cm}{\@author} \\
\end{tabular}

\vskip 1em
\begin{tabular}{ p{3cm} l }
\ifthenelse{\equal{\languagename}{\string ngerman}}{Hauptbetreuer}{betr} & \parbox[t]{5cm}{\betreuer} \\
\end{tabular}

\vskip 1em
\begin{tabular}{ p{3cm} l }
\ifthenelse{\equal{\languagename}{\string ngerman}}{Nebenbetreuer}{neben} & \parbox[t]{5cm}{\nebenbetreuer} \\
\end{tabular}

\vskip 1em
\begin{tabular}{ p{3cm} l }
\ifthenelse{\equal{\languagename}{\string ngerman}}{Datum}{dat} & \parbox[t]{5cm}{\@date} \\
\end{tabular}

% Second page with the contact information
\newpage
\begin{flushleft}
\ifthenelse{\equal{\languagename}{\string ngerman}}{\textbf{Kontakt Adresse}}{\textbf{Contact Information}}\newline
c/o Inst. of Embedded Systems (InES)\newline
Zürcher Hochschule für Angewandte Wissenschaften \newline
Technikumstrasse 22\newline
CH-8401 Winterthur\newline
\newline
Tel.: +41 (0)58 934 75 25\newline
Fax.: +41 (0)58 935 75 25\newline
\newline
E-Mail: \Email\newline
Homepage: \url{http://www.ines.zhaw.ch}\newline
\end{flushleft}
\pagebreak
}



% Listing
% -----------------------------------------------------------------

%listing colors
\definecolor{lgray}{RGB}{250,250,250}
\definecolor{lgreen}{RGB}{63,127,95}
\definecolor{lred}{RGB}{127,0,85}
\definecolor{lblue}{RGB}{42,0,255}


\lstset{		
		basicstyle=\small\ttfamily,
		frame=single,
		numbers=left,	
		numberstyle=\tiny,
		numberblanklines=true,
		captionpos=b,
		extendedchars=true,
		float=ht,
		showtabs=false,
		tabsize=2,
		showspaces=false,
		showstringspaces=false,
		breaklines=true,
		backgroundcolor=\color{lgray},
		keywordstyle=\color{lred}\bfseries, 
		commentstyle=\color{lgreen}\ttfamily,
		stringstyle=\color{lblue},
		xleftmargin=0.5cm,
		xrightmargin=0.5cm
}

\lstloadlanguages{C++}
